services:
  api-jump-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-web-uuid
    healthcheck:
      interval: 10s
      start_period: 10s
      retries: 3
      timeout: 10s
      test:
        - CMD
        - /usr/local/bin/python
        - -c
        - |
          import http.client, sys
          conn = http.client.HTTPConnection('localhost', 8080, timeout=10)
          conn.request('GET', '/health')
          r = conn.getresponse()
          sys.exit(0 if r.status == 200 else 1)
    deploy:
      resources:
        limits:
          cpus: "0.333"
          memory: 512M
        reservations:
          cpus: "0.167"
          memory: 256M
    ports:
      - "8080:8080"
