---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-uuid
  namespace: web
  labels:
    app: simple-web-uuid
    app.kubernetes.io/component: simple-web-uuid
    app.kubernetes.io/instance: simple-web-uuid
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: simple-web-uuid
    app.kubernetes.io/part-of: web
spec:
  selector:
    matchLabels:
      app: simple-web-uuid
      app.kubernetes.io/component: simple-web-uuid
      app.kubernetes.io/instance: simple-web-uuid
      app.kubernetes.io/managed-by: kubectl
      app.kubernetes.io/name: simple-web-uuid
      app.kubernetes.io/part-of: web
  template:
    metadata:
      labels:
        app: simple-web-uuid
        app.kubernetes.io/component: simple-web-uuid
        app.kubernetes.io/instance: simple-web-uuid
        app.kubernetes.io/managed-by: kubectl
        app.kubernetes.io/name: simple-web-uuid
        app.kubernetes.io/part-of: web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                      - k3s
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - simple-web-uuid
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - simple-web-uuid
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - simple-web-uuid
                    - key: app.kubernetes.io/managed-by
                      operator: In
                      values:
                        - kubectl
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - simple-web-uuid
                    - key: app.kubernetes.io/part-of
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      imagePullSecrets:
        - name: ghrc-assisjrt
      automountServiceAccountToken: false
      serviceAccountName: simple-web-uuid
      securityContext:
        runAsNonRoot: true
        runAsUser: 65536
        runAsGroup: 65536
        fsGroup: 65536
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile:
          type: RuntimeDefault
        # appArmorProfile:
        #   type: RuntimeDefault
      containers:
        - name: simple-web-uuid
          image: ghcr.io/assisjrt/simple-web-uuid:latest
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 65536
            runAsGroup: 65536
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          env:
            - name: TZ
              value: "America/Sao_Paulo"
            - name: LANG
              value: "en_US.UTF-8"
            - name: LANGUAGE
              value: "en_US.UTF-8"
            - name: LC_ALL
              value: "en_US.UTF-8"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
          resources:
            requests:
              cpu: 83m
              memory: 128Mi
            limits:
              cpu: 83m
              memory: 128Mi
