---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-uuid
  namespace: web
  labels:
    app: simple-web-uuid
    app.kubernetes.io/component: simple-web-uuid
    app.kubernetes.io/instance: simple-web-uuid
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: simple-web-uuid
    app.kubernetes.io/part-of: web
spec:
  type: LoadBalancer
  selector:
    app: simple-web-uuid
    app.kubernetes.io/component: simple-web-uuid
    app.kubernetes.io/instance: simple-web-uuid
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/name: simple-web-uuid
    app.kubernetes.io/part-of: web
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
