name: Build and Push to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login in GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest

      - name: Checkout manifests repository
        uses: actions/checkout@v4
        with:
          repository: assisjrt/kubernetes-manifests-public
          ssh-key: ${{ secrets.DEPLOY_KEY_KUBERNETES_MANIFESTS_PUBLIC }}
          ref: main
          path: manifests

      - name: Update image tag in manifests
        run: |
          sed -i \
            "s|ghcr.io/${{ github.repository }}:.*|ghcr.io/${{ github.repository }}:${{ github.sha }}|" \
            ./manifests/simple-web-uuid/manifests/deploy.yaml

      - name: Commit and push changes
        run: |
          cd manifests
          git config user.name "actions-simple-web-uuid"
          git config user.email "actions-simple-web-uuid@github.com"
          git add .
          git commit -m "Update image in simple-web-uuid/manifests/deploy.yaml with ghcr.io/${{ github.repository }}:${{ github.sha }}"
          git push
